import { Geist, Geist_Mono } from 'next/font/google';
import './_css/globals.css';
import 'fontsource-montserrat/index.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'My Portfolio Website',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ja">
      <head>
        <meta charSet="UTF-8" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-teal-500 text-white shadow-md">
          <nav className="flex items-center justify-between p-4">
            <Link href="/">Home</Link>
            <Link href="/blog">Blog</Link>
          </nav>
        </header>
        <div className="mx-auto mt-4 max-w-2xl px-5 sm:mt-16">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
